"""Change m2m posts-tags

Revision ID: 15db44dc2fcc
Revises: 9c676e7acdad
Create Date: 2022-08-01 12:45:53.433879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15db44dc2fcc'
down_revision = '9c676e7acdad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
