"""Add activation code

Revision ID: 2cc3d2432db4
Revises: fa35bd9ab4ae
Create Date: 2022-07-27 12:45:28.438771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc3d2432db4'
down_revision = 'fa35bd9ab4ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_code')
    # ### end Alembic commands ###
